#!/usr/bin/env bash

copy_ci_artifacts() {
    set -xeuo pipefail;
    echo Copying CI artifacts

    mkdir -p "$ARTIFACTS_DIR"

    cp -r /tmp/out          "$ARTIFACTS_DIR"
    cp -r /tmp/conda-build  "$ARTIFACTS_DIR"
}

build_cunumeric_ci() {
    set -xeuo pipefail;

    printf "\n\n\n\n********* BUILDING CUNUMERIC CPP *********\n"
    build-cunumeric-cpp;

    printf "\n\n\n\n********* BUILDING CUNUMERIC WHEEL *********\n"
    build-cunumeric-wheel;

    printf "\n\n\n\n********* BUILDING CUNUMERIC CONDA *********\n"
    build-cunumeric-conda;

    copy_ci_artifacts;
}

build_cunumeric() {
    set -x;

    . conda-utils;
    . setup-utils;

    export BUILD_TYPE=$1

    set -xeuo pipefail;

    set_base_defs;

    cd "$PREBUILD_DIR"

    setup_build_env;
    init_sccache;
    cd "$REPO_DIR";

    rm -rf "$REPO_DIR/build";

    make-conda-env "$BUILD_TYPE";

    activate_conda_env;
    conda_info;

    case "$BUILD_TYPE" in
        ci) build_cunumeric_ci;;
        # release) build_cunumeric_release;;
        *) return 1;;
    esac
}

build_cunumeric_fake() {
    set -xeuo pipefail;

    mkdir -p /tmp/out /tmp/conda-build/legate_core /tmp/conda-build/cunumeric
    touch /tmp/out/legate-core-23.11.00-dummy.tar.bz2
    touch /tmp/conda-build/legate_core/dummy.txt
    touch /tmp/conda-build/cunumeric/dummy.txt

    copy_ci_artifacts
}


(build_cunumeric "$@");
