#!/usr/bin/env bash
set -x

#

copy_ci_artifacts() {
    set -xeuo pipefail;
    echo Copying CI artifacts

    mkdir -p "$ARTIFACTS_DIR"

    cp -r /tmp/out          "$ARTIFACTS_DIR"
    cp -r /tmp/conda-build  "$ARTIFACTS_DIR"
}

build_ci_product() {
    set -xeuo pipefail;

    printf "\n\n\n\n********* BUILDING CUNUMERIC CPP *********\n"
    build-cunumeric-cpp;

    printf "\n\n\n\n********* BUILDING CUNUMERIC WHEEL *********\n"
    build-cunumeric-wheel;

    printf "\n\n\n\n********* BUILDING CUNUMERIC CONDA *********\n"
    build-cunumeric-conda;

    copy_ci_artifacts;
}

build_cunumeric_fake() {
    set -xeuo pipefail;

    mkdir -p /tmp/out /tmp/conda-build/legate_core /tmp/conda-build/cunumeric
    touch /tmp/out/legate-core-23.11.00-dummy.tar.bz2
    touch /tmp/conda-build/legate_core/dummy.txt
    touch /tmp/conda-build/cunumeric/dummy.txt

    copy_ci_artifacts
}

build_project() {
    . setup-utils;

    init_build_env "$@";

    case "$BUILD_TYPE" in
        ci) build_ci_product;;
        release) build_release;;
        *) return 1;;
    esac
}


(build_project "$@");
