#!/usr/bin/env bash

set_repo_dir() {
    set -xeuo pipefail

    # Resolve the directory of the script
    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

    # Navigate to the parent of the parent of SCRIPT_DIR, then get the full path
    REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

    export REPO_DIR

    export PATH="${PATH}:${REPO_DIR}/continuous_integration/scripts"

    # export ARTIFACTS_DIR=${ARTIFACTS_DIR:-/tmp/artifacts}
}

entrypoint() {
    set -xeuo pipefail
    set_repo_dir;

    exec "$@";
}

entrypoint "$@";
