#!/usr/bin/env bash

set -x

. conda-utils

make_ci_env() {
    set -xeuo pipefail
    yaml_file=$(find "${ARTIFACTS_DIR}" -name "environment*.yaml" | head -n 1)

    [ "${USE_CUDA}" = "ON" ] &&
        echo "  - libcublas-dev" >> "${yaml_file}" &&
        echo "  - libcufft-dev" >> "${yaml_file}" &&
        echo "  - libcurand-dev" >> "${yaml_file}" &&
        echo "  - libcusolver-dev" >> "${yaml_file}";

    echo "YAML file..."
    cat "${yaml_file}"

    mkdir -p /tmp/out;

    cp "${yaml_file}" /tmp/out

    mamba env create -n legate -f "$yaml_file"

    mamba uninstall -yn legate numpy

    mamba install -yn legate -c "${ARTIFACTS_DIR}/conda-build/legate_core" -c conda-forge -c nvidia legate-core
}

make_conda_env() {
    set -xeuo pipefail

    case "$1" in
        ci) make_ci_env;;
        release) make_release_env;;
        *) return 1;;
    esac

    return 0;
}

(make_conda_env "$@");